language: node_js
node_js:
  - '6'
script:
  - yarn run test
  - yarn
  - yarn run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master